Feature: SM-1086 — Test Plan — SM-1086: PWA PTO Module
  Jira: SM-1086
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

  @SC-01 @SM-1086
  Scenario: SC-01 — TODO (generation failed)
    Given TODO
