Feature: SM-1089 — Test Plan — SM-1089: PWA Work Orders Module
  Jira: SM-1089
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard
@SC-01 @SM-1089
Scenario: Hamburger menu reveals both Work Orders navigation entries
  Given I am logged in and on the dashboard
  When I open the hamburger menu in the PWA
  Then I should see the "Work Orders" menu item
  And I should see the "Work Order Map" menu item

  @SC-02 @SM-1089
  Scenario: SC-02 — TODO (generation failed)
    Given TODO

  @SC-03 @SM-1089
  Scenario: SC-03 — TODO (generation failed)
    Given TODO

  @SC-04 @SM-1089
  Scenario: SC-04 — TODO (generation failed)
    Given TODO

  @SC-05 @SM-1089
  Scenario: SC-05 — TODO (generation failed)
    Given TODO

  @SC-06 @SM-1089
  Scenario: SC-06 — TODO (generation failed)
    Given TODO

  @EC-01 @SM-1089
  Scenario: EC-01 — TODO (generation failed)
    Given TODO
