Feature: SM-1114 — Test Plan — SM-1114: Prevent Saving Invalid Clock In/Out Times in PWA
  Jira: SM-1114
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard
@SC-01 @SM-1114
Scenario: Valid time entry saves successfully
  Given I am logged in and on the dashboard
  When I navigate to the Timesheets module
  And I select the current time period
  And I enter valid hours for a work order on a working day
  And I save the time entry
  Then the time entry should be saved successfully
  And the saved hours should be visible in the timesheet

  @SC-02 @SM-1114
  Scenario: SC-02 — TODO (generation failed)
    Given TODO

  @SC-03 @SM-1114
  Scenario: SC-03 — TODO (generation failed)
    Given TODO

  @SC-04 @SM-1114
  Scenario: SC-04 — TODO (generation failed)
    Given TODO

  @SC-05 @SM-1114
  Scenario: SC-05 — TODO (generation failed)
    Given TODO

  @SC-06 @SM-1114
  Scenario: SC-06 — TODO (generation failed)
    Given TODO

  @EC-01 @SM-1114
  Scenario: EC-01 — TODO (generation failed)
    Given TODO

  @EC-02 @SM-1114
  Scenario: EC-02 — TODO (generation failed)
    Given TODO
