Feature: SM-1143 — Test Plan — SM-1143: Restore Vendor Visibility on POR Quote Lines
  Jira: SM-1143
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1143
Scenario: PO Detail selected line panel and POR review display vendor names
  Given I am logged in and on the dashboard
  When I navigate to Purchasing and open a purchase order that has a vendor assigned
  And I select a line item in the PO detail view
  Then the selected line panel should display the vendor name
  When I open the POR review for that purchase order
  Then the vendor name should be visible in the POR review

@SC-02 @SM-1143
Scenario: PO export lines CSV contains Vendor column
  Given I am logged in and on the dashboard
  When I navigate to the Purchasing Tracker module
  And I export the purchase order lines as CSV
  Then the downloaded CSV contains a "Vendor" column header

@SC-03 @SM-1143
Scenario: PO PDF download shows vendor name on each line item
  Given I am on the Purchasing Tracker page
  When I open a purchase order that has multiple line items with different vendors
  And I download the PO as a PDF
  Then each line item in the downloaded PDF should display the associated vendor name

@SC-04 @SM-1143
Scenario: Quote detail page loads without hanging and displays vendor names
  Given I navigate to the Quoting module
  When I open an existing quote detail record
  Then the quote detail page should load completely without freezing
  And vendor names should be visible in the quote details

@SC-05 @SM-1143
Scenario: BOM export CSV shows vendor names and save does not log phantom vendor changes
  Given I navigate to the Vendor Admin BOM grid
  When I export the BOM grid to CSV and save a record without changing any vendor fields
  Then the downloaded file contains only the filtered rows and the "Vendor Name" column is populated
  And no vendor change entries should appear in the audit log

@SC-06 @SM-1143
Scenario: VP Override Approval Email Shows Vendor Name (Not "No Vendor")
  Given a work order expense linked to a known vendor requires VP override approval
  When a manager submits the VP override approval request
  Then the VP override approval email should display the vendor name and not "No Vendor"

@EC-01 @SM-1143
Scenario: Lines with no vendor assigned remain blank in the grid and exported file
  Given I am logged in and on the dashboard
  When I navigate to the module containing line items with no vendor assigned
  And I filter the grid to show only lines where no vendor has been assigned
  Then the vendor field for each unassigned line should appear blank in the grid
  And the exported file should show a blank vendor value for each unassigned line

@EC-02 @SM-1143
Scenario: Vendor rename propagates immediately to all read paths
  Given I navigate to the Vendor Admin module
  When I rename an existing vendor to a new unique name and save
  Then the updated vendor name should appear in the grid row immediately
  And the updated vendor name should appear in the vendor detail view
