Feature: SM-1084 — Test Plan — SM-1084: PWA Work Confirm Exception Module
  Jira: SM-1084
  Generated by TestGenerator step 6 on 2026-05-07

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1084
Scenario: Salaried user with Work Confirm Exception permission sees the sidebar menu item
  Given a user has the salaried flag enabled and Work Confirm Exception permission granted
  When I view the sidebar navigation
  Then I should see the "Work Confirm Exception" menu item
