Feature: SM-1115 — Test Plan — SM-1115: Prevent Unnecessary WO Validation Warning in PWA Expense Edit
  Jira: SM-1115
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard
@SC-01 @SM-1115
Scenario: Edit expense with non-scheduled WO saves successfully without modifying the WO field
  Given I am logged in and on the dashboard
  And I have an existing expense linked to a non-scheduled work order
  When I open the expense and edit a field other than the work order number
  And I save the expense without modifying the WO field
  Then the expense should be saved successfully without a validation error

  @SC-02 @SM-1115
  Scenario: SC-02 — TODO (generation failed)
    Given TODO

  @SC-03 @SM-1115
  Scenario: SC-03 — TODO (generation failed)
    Given TODO

  @SC-04 @SM-1115
  Scenario: SC-04 — TODO (generation failed)
    Given TODO

  @SC-05 @SM-1115
  Scenario: SC-05 — TODO (generation failed)
    Given TODO

  @EC-01 @SM-1115
  Scenario: EC-01 — TODO (generation failed)
    Given TODO

  @EC-02 @SM-1115
  Scenario: EC-02 — TODO (generation failed)
    Given TODO
