Feature: SM-1103 — Test Plan: SM-1103 — Project Cascade Template Management Screen
  Jira: SM-1103
  Generated by TestGenerator step 6 on 2026-04-29

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard
@SC-01 @SM-1103
Scenario: Navigate to Cascade Templates and verify the master-detail layout is displayed
  Given I am logged in and on the dashboard
  When I navigate to the Cascade Templates module
  Then I should see the template list with available templates
  And I should see the template detail panel

@SC-02 @SM-1103
Scenario: Create a new template and populate it with step items
  Given I navigate to the Cascade Templates module
  When I click the button to create a new template
  And I enter a name for the new template
  And I add multiple step items to the template
  And I save the template
  Then I should see the template list
  And the new template should appear in the list with its step items saved

@SC-03 @SM-1103
Scenario: Edit a template name and item days value and verify both persist after page refresh
  Given I navigate to the Cascade Templates module
  And a cascade template is open for editing
  When I update the template name to a new value
  And I update an item's days value to a new number
  And I save the template changes
  And I refresh the page
  Then the updated template name should be visible
  And the updated item days value should be visible

@SC-04 @SM-1103
Scenario: Reorder step items using up and down arrows and verify the new order persists
  Given I navigate to the Cascade Templates module
  And a cascade template is open for editing
  When I move a step down one position using the down arrow
  And I save the template
  And I reopen the same template for editing
  Then the steps should appear in the reordered sequence

@SC-05 @SM-1103
Scenario: Delete an item and delete a template via confirmation dialogs
  Given I navigate to the Cascade Templates module
  And a cascade template is open for editing
  When I delete a step from the template and confirm the deletion dialog
  Then the step should no longer appear in the template
  When I delete the template and confirm the deletion dialog
  Then the template should no longer appear in the template list

@EC-01 @SM-1103
Scenario: Add Item dialog shows a validation error when the number of days is empty, non-numeric, negative, or zero
  Given I am logged in and on the dashboard
  And I navigate to the Cascade Templates module
  And a cascade template is open for editing
  When I open the Add Item dialog and attempt to save with an invalid number of days
  Then I should see a validation error message

@EC-02 @SM-1103
Scenario: Template list search filters and restores correctly
  Given I navigate to the Cascade Templates module
  And I should see the template list with available templates
  When I enter a partial name in the template list search input
  Then only matching templates should be visible in the list
  When I clear the template list search input
  Then I should see the template list with available templates
