Feature: SM-1064 — Test Plan — SM-1064: Vendor Admin — Upload/Replace Company Logo
  Jira: SM-1064
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-02 @SM-1064
Scenario: Replace an existing logo in Edit mode
  Given a vendor record exists with a company logo already uploaded
  When I open that vendor in Edit mode in Vendor Admin
  And I upload a replacement image in the company logo section
  And I save the vendor record
  Then the vendor profile should display the newly uploaded logo

@SC-01 @SM-1064
Scenario: Upload logo for an existing vendor with no prior logo
  Given I navigate to the Vendor Admin module
  And I open a vendor record that has no company logo
  When I upload a logo image in the company logo section
  Then the uploaded logo should be displayed in the vendor profile

@SC-03 @SM-1064
Scenario: Upload logo during new vendor creation deferred upload
  Given I am on the Vendor Admin grid
  When I add a new vendor and upload a company logo before saving the record
  Then the company logo should be displayed on the newly created vendor profile

@EC-01 @SM-1064
Scenario: Non-PNG file is rejected with a clear error message
  Given I am logged in and on the dashboard
  When I navigate to the Vendor Admin company logo section and upload a non-PNG file
  Then I should see a validation error message

@EC-02 @SM-1064
Scenario: Logo panel collapse and re-expand preserves staged file selection
  Given I am on the Vendor Admin page with a vendor profile open
  When I expand the Upload Replace Company Logo section
  And I select a file in the logo upload input without saving
  And I collapse the Upload Replace Company Logo section
  And I expand the Upload Replace Company Logo section again
  Then the selected file name should still be displayed in the logo upload input

@SC-04 @SM-1064
Scenario: Company logo uploaded in new Vendor Admin is visible in old Vendor Admin
  Given I am logged in and on the dashboard
  When I open a vendor record in the new Vendor Admin and upload a company logo
  Then the same logo should be visible for that vendor in the old Vendor Admin view
