Feature: SM-1099 — Test Plan — SM-1099: Log Processing for Errors and Debug Information
  Jira: SM-1099
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1099
Scenario: Log processing with populated logs creates a Jira ticket
  Given the application error log contains entries for today
  When the log processing cron job runs
  Then a new Jira defect ticket is created and assigned to the primary developer

@SC-02 @SM-1099
Scenario: Empty or absent log files produce no Jira ticket
  Given the application log files are empty or do not exist
  When the log processing job runs
  Then no Jira ticket should be created in the SM project

@SC-03 @SM-1099
  Scenario: Jira API failure is handled gracefully without crashing
    Given the log processing service is running and logs are available for analysis
    When the Jira API is unavailable during the ticket creation attempt
    Then the log processing run completes without crashing
    And a failure notice is recorded in the processing output
    And no partial or corrupt Jira ticket is left in an unknown state

@SC-04 @SM-1099
Scenario: Jira credentials are not exposed in the admin keys table
  Given I am logged in and on the dashboard
  When I navigate to the admin keys table
  Then the Jira credentials should not be visible in plain text

@SC-05 @SM-1099
Scenario: Cron record exists and is disabled by default
  Given I navigate to the Cron Utility admin page
  When I locate the log processing cron job record
  Then the cron record should be present and disabled by default

@EC-01 @SM-1099
Scenario: Log processing admin screen is not accessible to non-admin users
  When I navigate to the log processing admin screen
  Then I should see a validation error message

@EC-02 @SM-1099
Scenario: Duplicate run on same day does not create a second Jira ticket
  Given a record with the same identifying value already exists in the system
  When the log processing pipeline runs again for the same day
  Then exactly one submission should be recorded
  And no additional duplicate record should be created
