Feature: SM-1146 — Test Plan — SM-1146: Logs from Production
  Jira: SM-1146
  Generated by TestGenerator step 6 on 2026-05-07

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard
  @SC-01 @SM-1146
  Scenario: SC-01 — TODO (generation failed)
    Given TODO

  Scenario: SC-01 — TODO (generation failed)
    Given TODO
