Feature: SM-1120 — Test Plan — SM-1120: Quote PO Line – Missing Vendors in Dropdown
  Jira: SM-1120
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1120
Scenario: New PO line vendor dropdown is fully populated
  Given I am logged in and on the dashboard
  When I navigate to the Purchasing module and open a new PO line
  Then the vendor dropdown should contain at least one vendor option

@SC-02 @SM-1120
Scenario: Existing PO line vendor dropdown is fully populated on edit
  Given I navigate to the Purchasing module
  When I open an existing purchase order line for editing
  Then the vendor dropdown should be fully populated with available options

@SC-03 @SM-1120
Scenario: Vendor names in dropdown match Vendor Admin records
  Given I am on the dashboard
  When I navigate to the Vendor Admin module
  And I collect the vendor names from the Vendor Admin grid
  And I navigate to the module containing the vendor selection dropdown
  Then all collected vendor names should appear as options in the dropdown

@SC-04 @SM-1120
Scenario: Vendor selection saves and persists on a new PO line
  Given I navigate to the Purchasing module
  When I open a new purchase order
  And I select a vendor on the first PO line
  And I save the purchase order
  And I add a new line to the purchase order
  Then the vendor on the first line should still display the originally selected vendor

@EC-01 @SM-1120
Scenario: Vendor dropdown is searchable and filters the full vendor list
  Given I am on the Vendor Admin page
  When I open the vendor dropdown and type a partial vendor name
  Then only vendors matching the search term should appear in the dropdown list

@EC-02 @SM-1120
Scenario: PO line with previously-saved blank vendor loads without freezing
  Given a purchase order line with a blank vendor field exists in the system
  When I navigate to the Purchasing Tracker and open that purchase order line
  Then the Purchasing Tracker page should remain interactive without freezing
