Feature: SM-1106 — SM-1106 — Stage Test Plan
  Jira: SM-1106
  Generated by TestGenerator step 6 on 2026-05-07

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@EC-01 @SM-1106
Scenario: WO with null starting field value produces blank cascade dates without crashing
  Given I navigate to the Cascade Templates module
  And a cascade template is open for editing
  When I apply the cascade template to a work order where the starting field value is null
  Then the cascade date fields should all be blank
  And the page should remain functional without errors
