Feature: Test Plan: SM-1105 — Set Default Template in Cascade Template Management Tool
  Jira: SM-1105
  Generated by bite step 6 on 2026-04-15

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

  @TC-1 @SM-1105
  Scenario: Set a cascade template as default via the three-dot menu
    When I click the "Project Admin" sidebar parent menu
    Then the "Project Admin" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    And I should see the template list with available templates
    When I note the current default template state
    And I click the three-dot menu on a non-default template
    Then I should see the "Set as Default" menu item in the context menu
    When I click the "Set as Default" menu item
    Then I should see the gold star icon next to the selected template
    And the template list should refresh automatically

  @TC-2 @SM-1105
  Scenario: Setting a new default template removes the previous default so only one exists at a time
    When I navigate to the Cascade Templates admin screen
    Then I should see the template list
    When I click the three-dot menu on the first template
    And I click the "Set as Default" menu option
    Then I should see the gold star icon next to the first template
    When I click the three-dot menu on a different template
    And I click the "Set as Default" menu option
    Then I should see the gold star icon next to the second template
    And the first template should no longer display the gold star icon
    And exactly one gold star icon should be visible in the template list
    When I click the three-dot menu on the first template
    Then the menu should show the "Set as Default" option

  @TC-3 @SM-1105
  Scenario: Default template gold star persists after full page reload
    When I navigate to the Cascade Templates admin screen
    Then I should see the template list
    When I click the three-dot menu on a non-default template
    And I click the "Set as Default" menu option
    Then I should see a gold star icon next to the selected template name
    When I note the default template name
    And I reload the page
    Then I should see the template list
    And I should see a gold star icon next to the same template name
    And no other template should display a gold star icon

  @TC-4 @SM-1105
  Scenario: Remove default designation leaves no template as default
    When I click the "Admin" sidebar parent menu
    Then the "Admin" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    And I should see the gold star icon on the current default template
    When I click the three-dot menu on the default template
    Then I should see the "Remove Default" menu option
    When I click the "Remove Default" menu option
    Then the gold star icon should disappear from the template
    And no template in the list should display a gold star icon
    When I click the "Refresh" button
    Then no template in the list should display a gold star icon

  @TC-5 @SM-1105
  Scenario: Context menu shows correct option based on default state
    When I click the "Admin" sidebar parent menu
    Then the "Admin" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I set template "A" as default
    Then the template "A" should display the default star icon
    When I click the three-dot menu on template "A"
    Then I should see the "Remove Default" menu option
    When I close the context menu
    And I click the three-dot menu on template "B"
    Then I should see the "Set as Default" menu option
    When I close the context menu
    And I click the three-dot menu on template "C"
    Then I should see the "Set as Default" menu option
    When I close the context menu
    And I click the three-dot menu on template "A"
    And I click the "Remove Default" menu option
    Then no template should display the default star icon
    When I click the three-dot menu on template "A"
    Then I should see the "Set as Default" menu option

  @TC-6 @SM-1105
  Scenario: Editing the default template name preserves the default star icon
    
    When I navigate to the Cascade Templates admin screen
    Then I should see the template list
    When I click the three-dot menu on the first template
    And I click the "Set as Default" menu option
    Then I should see the gold star icon next to the first template
    When I click on the first template to open the edit form
    And I change the template name to "Renamed Default Template"
    And I click the "Save" button
    Then I should see the template "Renamed Default Template" in the list
    And I should see the gold star icon next to template "Renamed Default Template"
    When I refresh the page
    Then I should see the gold star icon next to template "Renamed Default Template"
    And exactly one gold star icon should be visible in the template list

  @TC-7 @SM-1105
  Scenario: Deleting the default template removes the default designation cleanly
    When I navigate to the Cascade Templates admin screen
    Then I should see the template list
    When I create a new template named "Delete Me Test"
    Then I should see the template "Delete Me Test" in the list
    When I click the three-dot menu on template "Delete Me Test"
    And I click the "Set as Default" menu option
    Then I should see the gold star icon next to template "Delete Me Test"
    When I click the three-dot menu on template "Delete Me Test"
    And I click the "Delete" menu option
    And I confirm the deletion
    Then the template "Delete Me Test" should be removed from the list
    And no template should display the gold star icon
    When I refresh the page
    Then no template should display the gold star icon
    And I should not see any error messages

  @TC-8 @SM-1105
  Scenario: New template does not inherit values from the default template
    When I click the "Admin" sidebar parent menu
    Then the "Admin" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I click the "New Item" button
    Then I should see a blank template form with no pre-filled values from the default template
    And the step names should be empty
    And the number of days per step should be empty

  @TC-9 @SM-1105
  Scenario: Default template is used as fallback for projects without an explicit assignment
    When I navigate to the Cascade Templates admin screen
    Then I should see the template list
    When I set "Template A" as the default template
    Then I should see the gold star icon next to "Template A"
    When I navigate to the Projects Admin screen
    And I find a project with no explicitly assigned cascade template
    Then the project should use "Template A" as its cascade template

  @TC-10 @SM-1105
  Scenario: Changing default template propagates to projects without explicit assignments
    When I click the "Project Tracker" sidebar parent menu
    Then the "Project Tracker" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I set template "Template A" as the default
    Then I should see the gold star icon on "Template A"
    When I navigate to project admin for a project with no explicit template assignment
    Then the project should use cascade template "Template A"
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I set template "Template B" as the default
    Then I should see the gold star icon on "Template B"
    And I should not see the gold star icon on "Template A"
    When I navigate to project admin for a project with no explicit template assignment
    Then the project should use cascade template "Template B"

  @EC-1 @SM-1105
  Scenario: Rapid double-click on Set as Default button should not cause duplicate requests or errors
    When I click the "Admin" sidebar parent menu
    Then the "Admin" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I select the first cascade template from the list
    And I rapidly double-click the "Set as Default" button
    Then I should see exactly one success confirmation message
    And the selected template should be marked as the default
    And no duplicate or error messages should be displayed

  @EC-2 @SM-1105
  Scenario: Already-default template shows Remove Default instead of Set as Default
    When I navigate to the Cascade Templates admin screen
    Then I should see the cascade templates list
    When I click the three-dot menu on a non-default template
    And I click "Set as Default"
    Then the gold star icon should appear next to the selected template
    When I click the three-dot menu on the default template
    Then I should see the "Remove Default" menu option
    And I should not see the "Set as Default" menu option

  @EC-3 @SM-1105
  Scenario: Concurrent default template changes across two browser tabs resolve with last write wins
    When I navigate to the Cascade Templates admin screen
    Then I should see the cascade templates list
    And at least two templates should be present in the list
    When I open the Cascade Templates admin screen in a second browser tab
    Then both tabs should show the same template list
    When I set the first template as default in Tab 1
    Then the gold star icon should appear next to the first template in Tab 1
    When I set the second template as default in Tab 2 without refreshing
    Then the gold star icon should appear next to the second template in Tab 2
    When I refresh the Cascade Templates page in both tabs
    Then both tabs should show the second template as the default
    And only one gold star icon should be visible in each tab
    And no error messages should be displayed in either tab

  @EC-4 @SM-1105
  Scenario: Browser back and forward navigation returns to correct pages
    When I click the "Admin" sidebar parent menu
    And I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I navigate back in the browser
    Then I should be on the dashboard
    When I navigate forward in the browser
    Then I should see the page title "Cascade Templates"

  @EC-5 @SM-1105
  Scenario: Set and remove default when only one template exists in the system
    When I click the "Project Tracker" sidebar parent menu
    Then the "Project Tracker" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    And only one template should be visible in the template list
    When I click the three-dot menu on the only template
    And I click the "Set as Default" menu option
    Then a gold star icon should appear next to the template name
    When I click the three-dot menu on the only template
    Then I should see the "Remove Default" menu option
    When I click the "Remove Default" menu option
    Then no gold star icon should be visible in the template list

  @EC-6 @SM-1105
  Scenario: API error is handled gracefully when network drops during cascade template save
    When I click the "Project Admin" sidebar parent menu
    And I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When the network connection is interrupted
    And I click the "Save" button
    Then I should see an error message indicating the save failed
    And no template data should be lost or corrupted
    When the network connection is restored
    And I click the "Save" button
    Then the template should be saved successfully

  @EC-7 @SM-1105
  Scenario: Non-default template menu options unchanged after Set as Default feature added
    When I click the "Admin" sidebar parent menu
    Then the "Admin" submenu should expand
    When I click the "Cascade Templates" sidebar menu item
    Then I should see the page title "Cascade Templates"
    When I click the three-dot menu on a non-default template
    Then the template context menu should be visible
    And I should see the "Edit" menu option
    And I should see the "Delete" menu option
    And I should see the "Set as Default" menu option
    And no pre-existing menu options should be missing or displaced

