Feature: SM-1105 — Test Plan — SM-1105: Set Default Template in Cascade Template Management Tool
  Jira: SM-1105
  Generated by TestGenerator step 6 on 2026-05-07

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1105
Scenario: Set a template as default and verify the gold star indicator appears
  Given I navigate to the Cascade Templates module
  When I set the first template as default
  Then I should see the gold star icon next to the selected template
  And exactly one gold star icon should be visible in the template list
