Feature: SM-1126 — Test Plan — SM-1126: Project Tracker Duration Field Override
  Jira: SM-1126
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard
@SC-01 @SM-1126
Scenario: Authorized user overrides a duration and downstream dates recalculate instantly
  Given I navigate to the Cascade Templates module
  When I open an existing cascade template
  And I override the duration for a step to "10"
  Then the downstream dates for all subsequent steps should update immediately

Scenario: Permitted user edits a duration field and all downstream dates recalculate in real time
  Given I am logged in and on the dashboard
  When I navigate to the Cascade Templates management screen
  And I open an existing cascade template with multiple steps
  And I change the duration value of an intermediate step
  Then all downstream step dates in the template should update automatically to reflect the new duration

  Scenario: Edit-permitted user overrides step duration and all downstream dates recalculate instantly
    Given I navigate to the Cascade Template Management screen
    And a cascade template is open for editing
    When I change the duration of a step to a different number of days
    Then the downstream step dates should recalculate automatically without requiring a save

  @SC-02 @SM-1126
  Scenario: SC-02 — TODO (generation failed)
    Given TODO

  @SC-03 @SM-1126
  Scenario: SC-03 — TODO (generation failed)
    Given TODO

  @SC-04 @SM-1126
  Scenario: SC-04 — TODO (generation failed)
    Given TODO

  @SC-05 @SM-1126
  Scenario: SC-05 — TODO (generation failed)
    Given TODO

  @SC-06 @SM-1126
  Scenario: SC-06 — TODO (generation failed)
    Given TODO

  @EC-01 @SM-1126
  Scenario: EC-01 — TODO (generation failed)
    Given TODO

  @EC-02 @SM-1126
  Scenario: EC-02 — TODO (generation failed)
    Given TODO
