Feature: SM-1053 — Test Plan — SM-1053: Vendor Admin — Update Address Field Location
  Jira: SM-1053
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1053
Scenario: Address field appears in the Address section with correct label and is marked required when adding a new vendor
  Given I am logged in and on the dashboard
  When I navigate to the Vendor Admin module and open the Add New Vendor form
  Then the Address field should be visible within the Address section
  And the Address field should be labeled "Address"
  And the Address field should be marked as required

@SC-02 @SM-1053
Scenario: Edit vendor via pencil icon shows the updated address field location
  Given I am logged in and on the dashboard
  When I navigate to the Vendor Admin module
  And I click the pencil icon on an existing vendor record
  Then the address field should be visible in the updated location within the edit form

@SC-03 @SM-1053
Scenario: Required field validation blocks submission when required address fields are empty in both forms
  Given I am logged in and on the dashboard
  When I navigate to the Vendor Admin module
  And I open a vendor record for editing
  And I clear all required address fields in the inline grid form
  And I attempt to save the inline grid form
  Then I should see a validation error message
  When I open the same vendor record in the detail modal form
  And I clear all required address fields in the detail modal form
  And I attempt to save the detail modal form
  Then I should see a validation message preventing the save

@EC-01 @SM-1053
Scenario: Pre-existing vendor address value is preserved after address field relocation
  Given a vendor record exists with a saved address value
  When I navigate to the Vendor Admin module and open that vendor record
  Then the address field displays the original saved address value in its new location

@EC-02 @SM-1053
Scenario: Address textarea appears before City, State, and Zip in the address section
  Given I navigate to the Vendor Admin module
  When I open a vendor record for editing
  Then the Address field should appear above the City, State, and Zip fields in the address section
