Feature: SM-1088 — Test Plan — SM-1088: PWA Work Confirmation Module
  Jira: SM-1088
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-1088
Scenario: Work Confirmation module is accessible and displays a 3-day grid layout
  Given I am logged in and on the dashboard
  When I navigate to the Work Confirmation module in the PWA
  Then I should see the page title "Work Confirmation"
  And I should see the 3-day grid layout
