Feature: SM-742 — Test Plan: SM-742 — Prevent Duplicate Departments in Maintenance Admin
  Jira: SM-742
  Generated by TestGenerator step 6 on 2026-04-22

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-742
Scenario: Add a unique department successfully
  Given I am logged in and on the dashboard
  When I click the "Admin" sidebar parent menu
  And I click the "Departments" sidebar menu item
  And I click the "Add Department" button
  And I enter a unique department name
  And I click the "Save" button
  Then the new department should appear in the departments list


@SC-02 @SM-742
Scenario: Block exact duplicate department name
  Given I am logged in and on the dashboard
  When I click the "Admin" sidebar parent menu
  And I click the "Departments" sidebar menu item
  And I click the "Add" button
  And I enter the name of an existing department
  And I click the "Save" button
  Then I should see a validation error blocking the duplicate department name


@SC-03 @SM-742
Scenario: Case-insensitive duplicate template name is blocked
  Given I am logged in and on the dashboard
  When I navigate to the Cascade Templates admin screen
  And I create a cascade template named "Alpha Project"
  And I attempt to create a cascade template named "alpha project"
  Then I should see a duplicate name validation error


@SC-04 @SM-742
Scenario: Leading and trailing whitespace is trimmed before search comparison
  Given I am logged in and on the dashboard
  When I type "  testserver  " in the navbar search input
  Then I should be navigated to search results


@EC-01 @SM-742
Scenario: Submitting a whitespace-only value is rejected with a validation error
  Given I am logged in and on the dashboard
  When I submit the form with a whitespace-only value
  Then I should see a validation error message requiring a non-empty value


@EC-02 @SM-742
Scenario: Server-side duplicate check rejects a duplicate record when frontend validation is bypassed
  Given I am logged in and on the dashboard
  And a record with the same identifying value already exists in the system
  When I submit a second record with the same identifying value bypassing the frontend duplicate check
  Then the system should display a duplicate entry error message
  And no additional duplicate record should be created



  # --- SM-742 scenarios added 2026-04-26 ---

@SC-01 @SM-742
Scenario: Add a unique department successfully
  Given I am logged in and on the dashboard
  When I click the "Admin" sidebar parent menu
  And I click the "Departments" sidebar menu item
  And I click the "Add Department" button
  And I enter a unique department name
  And I click the "Save" button
  Then the new department should appear in the departments list


@SC-02 @SM-742
Scenario: Block exact duplicate department name
  Given I am logged in and on the dashboard
  When I click the "Admin" sidebar parent menu
  And I click the "Departments" sidebar menu item
  And I click the "Add" button
  And I enter the name of an existing department
  And I click the "Save" button
  Then I should see a validation error blocking the duplicate department name


@SC-03 @SM-742
Scenario: Case-insensitive duplicate template name is blocked
  Given I am logged in and on the dashboard
  When I navigate to the Cascade Templates admin screen
  And I create a cascade template named "Alpha Project"
  And I attempt to create a cascade template named "alpha project"
  Then I should see a duplicate name validation error


@SC-04 @SM-742
Scenario: Leading and trailing whitespace is trimmed before search comparison
  Given I am logged in and on the dashboard
  When I type "  testserver  " in the navbar search input
  Then I should be navigated to search results


@EC-01 @SM-742
Scenario: Empty or whitespace-only department name is not saved
  Given I am logged in and on the dashboard
  When I click the "Maintenance" sidebar parent menu
  And I click the "Maintenance Admin" sidebar menu item
  And I enter "     " in the department name field and click the "Add" button
  Then no blank or whitespace department entry should appear in the list
  And I should see a validation message preventing the save


@EC-02 @SM-742
Scenario: Server-side duplicate check rejects a duplicate record when frontend validation is bypassed
  Given I am logged in and on the dashboard
  And a record with the same identifying value already exists in the system
  When I submit a second record with the same identifying value bypassing the frontend duplicate check
  Then the system should display a duplicate entry error message
  And no additional duplicate record should be created

