Feature: SM-775 — SM-775
  Jira: SM-775
  Generated by TestGenerator step 6 on 2026-04-22

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-775
Scenario: Alternate Approver Gains Rectify Access for Covered Manager's Employees
  Given I am logged in and on the dashboard
  And an alternate approver is configured to cover a manager with assigned employees
  When I log in as the alternate approver and navigate to the timesheet approval screen
  Then the alternate approver should see the Rectify option for each employee belonging to the covered manager


@SC-02 @SM-775
Scenario: Alternate approver access is revoked after removal
  Given I am logged in and on the dashboard
  When I navigate to the user whose alternate approver is being removed
  And I remove the alternate approver from that user
  Then the removed alternate approver should no longer have access to approve that user's records


@SC-03 @SM-775
Scenario: Existing direct manager rectify entry is unaffected by timesheet admin changes
  Given I am logged in and on the dashboard
  When I navigate to a timesheet that already has a direct manager rectify entry
  Then the direct manager rectify entry should remain intact and unchanged


@SC-04 @SM-775
Scenario: Alternate Approver Covering Multiple Managers Sees All Covered Employees
  Given I am logged in and on the dashboard
  When I click the "Timesheets" sidebar parent menu
  And I click the "Timesheet Admin" sidebar menu item
  Then I should see employees from all managers covered by the alternate approver assignment


@EC-01 @SM-775
Scenario: User with no alternate approver relationship cannot view another manager's employees
  Given I am logged in and on the dashboard
  When I click the "Timesheets" sidebar parent menu
  And I click the "Timesheet Admin" sidebar menu item
  Then I should not see employees belonging to other managers in the employee list


@EC-02 @SM-775
Scenario: Alternate approver cannot rectify timesheets for employees outside their approval scope
  Given I am logged in and on the dashboard
  When I navigate to the timesheet rectification screen as an alternate approver
  And I search for an employee who is not assigned to me
  Then the rectify action should not be available for that employee



  # --- SM-775 scenarios added 2026-04-26 ---

@SC-01 @SM-775
Scenario: Alternate Approver Gains Rectify Access for Covered Manager's Employees
  Given I am logged in and on the dashboard
  And an alternate approver is configured to cover a manager with assigned employees
  When I log in as the alternate approver and navigate to the timesheet approval screen
  Then the alternate approver should see the Rectify option for each employee belonging to the covered manager


@SC-02 @SM-775
Scenario: Removing alternate approver relationship revokes Rectify access
  Given a user has Rectify access granted through an Alternate Approver relationship
  When I remove the Alternate Approver relationship from that user's profile
  Then the user should no longer have Rectify access in the UAC system


@SC-03 @SM-775
Scenario: Existing direct manager rectify entry is unaffected by timesheet admin changes
  Given I am logged in and on the dashboard
  When I navigate to a timesheet that already has a direct manager rectify entry
  Then the direct manager rectify entry should remain intact and unchanged


@SC-04 @SM-775
Scenario: Alternate Approver Covering Multiple Managers Sees All Covered Employees
  Given I am logged in and on the dashboard
  When I click the "Timesheets" sidebar parent menu
  And I click the "Timesheet Admin" sidebar menu item
  Then I should see employees from all managers covered by the alternate approver assignment


@EC-01 @SM-775
Scenario: User with no alternate approver relationship cannot view another manager's employees
  Given I am logged in and on the dashboard
  When I click the "Timesheets" sidebar parent menu
  And I click the "Timesheet Admin" sidebar menu item
  Then I should not see employees belonging to other managers in the employee list


@EC-02 @SM-775
Scenario: Alternate approver cannot rectify timesheets for employees outside their approval scope
  Given I am logged in and on the dashboard
  When I navigate to the timesheet rectification screen as an alternate approver
  And I search for an employee who is not assigned to me
  Then the rectify action should not be available for that employee

