Feature: SM-754 — Test Plan — SM-754: Purchasing Tracker Filters
  Jira: SM-754
  Generated by TestGenerator step 6 on 2026-04-22

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-754
Scenario: Text and ID filters narrow the Purchasing Tracker table and exported file reflects only filtered rows
  Given I am logged in and on the dashboard
  When I navigate to the Purchasing Tracker
  And I filter the "ID" column by a known PO ID
  Then the table should narrow to only rows matching that ID
  When I click the "Export" button
  Then the exported file should contain only the filtered ID rows
  When I clear the "ID" filter and apply the "WO#" filter with a known WO number
  Then the table should narrow to only rows linked to that WO number
  When I click the "Export" button
  Then the exported file should contain only the filtered WO number rows
  When I clear the "WO#" filter and apply the "Description" filter with a partial keyword
  Then the table should narrow to only rows containing that keyword in the Description column
  When I clear the "Description" filter and apply the "PO#" filter with a known PO number
  Then the table should narrow to only rows matching that PO number
  When I click the "Export" button
  Then the exported file should contain only the filtered PO number rows


  @SC-02 @SM-754
  Scenario: SC-02 — TODO (generation failed)
    Given TODO


@SC-03 @SM-754
Scenario: Dropdown and selection filters narrow the purchasing tracker table and export correctly
  Given I am logged in and on the dashboard
  When I navigate to the Purchasing Tracker module
  Then the Division column should have no filter option
  When I apply the "Type" column filter with value "PO"
  Then the table should show only rows matching type "PO"
  When I click the "Export" button
  Then the exported file should contain only rows with type "PO"
  When I clear the "Type" column filter
  And I apply the "Status" column filter with a single status value
  Then the table should show only rows matching that status
  When I click the "Export" button
  Then the exported file should contain only rows matching that status
  When I clear the "Status" column filter
  And I apply the "Priority" column filter with value "High"
  Then the table should show only high priority rows
  When I clear the "Priority" column filter
  And I apply the "Dept" column filter with a known department
  Then the table should show only rows for that department
  And the Dept column header should show a filter active indicator
  When I clear the "Dept" column filter
  Then the Dept column header should show no filter active indicator
  When I apply the "Vendor" column filter with a known vendor
  Then the table should show only rows for that vendor
  When I click the "Export" button
  Then the exported file should contain only rows for that vendor
  When I clear the "Vendor" column filter
  And I apply the "Needs My Approval" column filter with value "Yes"
  Then the table should show only records requiring my approval
  When I click the "Export" button
  Then the exported file should complete successfully with only matching rows


@SC-04 @SM-754
Scenario: Approval and Approver(s) column filters include Blank option and export reflects blank-only rows
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  Then the Purchasing Tracker grid should be visible
  When I open the filter for the "Approval" column
  Then the filter dropdown should include the options "Approved", "Pending Approval", "Override", "Rejected", and "Blank"
  When I select "Blank" from the "Approval" column filter
  Then all visible rows should have an empty "Approval" value
  And rows with a non-empty "Approval" value should not be visible
  When I click the "Export" button
  Then the exported file should contain only rows with a blank "Approval" value
  When I clear the "Approval" column filter
  And I open the filter for the "Approver(s)" column
  And I select "Blank" from the "Approver(s)" column filter
  Then all visible rows should have an empty "Approver(s)" value
  And rows with a named approver should not be visible
  When I click the "Export" button
  Then the exported file should contain only rows with a blank "Approver(s)" value


@SC-05 @SM-754
Scenario: Clearing filters resets table state and removes column header filter indicators
  Given I am logged in and on the dashboard
  When I click the "Work Orders" sidebar parent menu
  And I click the "WO Tracker" sidebar menu item
  And I type "Engineering" in the sidebar filter
  Then I should see the sidebar filter
  When I click the "Dept" column header filter
  And I select "Engineering" from the filter dropdown
  Then the table should show only rows matching the "Engineering" department
  And the Dept column header should display a filter indicator
  When I clear the "Dept" column filter
  Then the table should display the full record set
  And the Dept column header should not display a filter indicator
  When I apply a "Status" filter of "Approved" and a "Priority" filter of "High"
  Then the table should show only rows matching both active filters
  And the Status column header should display a filter indicator
  And the Priority column header should display a filter indicator
  When I clear the "Status" filter
  Then the table should reflect only the remaining "Priority" filter
  And the Status column header should not display a filter indicator
  And the Priority column header should still display a filter indicator
  When I clear all filters
  Then the table should display the full record set
  And no column header should display a filter indicator


  @EC-01 @SM-754
  Scenario: EC-01 — TODO (generation failed)
    Given TODO


@EC-02 @SM-754
Scenario: Export completes without freezing when a large filtered result set is selected
  Given I am logged in and on the dashboard
  When I click the "Work Orders" sidebar parent menu
  And I click the "WO Tracker" sidebar menu item
  And I apply a broad date range filter that returns a large number of results
  And I click the "Export" button
  And I navigate to the export queue and refresh until the export is ready
  Then the export file should be available for download and contain data rows



  # --- SM-754 scenarios added 2026-04-22 ---

@SC-01 @SM-754
Scenario: Text and ID filters narrow the Purchasing Tracker table and exported file reflects only filtered rows
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I filter the "ID" column by a known PO ID
  Then the table should narrow to only rows matching that ID
  When I click the "Export" button
  Then the exported file should contain only the filtered ID rows
  When I clear the "ID" column filter
  And I filter the "WO#" column by a known WO number
  Then the table should narrow to only rows linked to that WO number
  When I click the "Export" button
  Then the exported file should contain only the filtered WO number rows
  When I clear the "WO#" column filter
  And I filter the "Description" column by a partial keyword
  Then the table should narrow to only rows containing that keyword in the Description column
  When I clear the "Description" column filter
  And I filter the "PO#" column by a known PO number
  Then the table should narrow to only rows matching that PO number
  When I click the "Export" button
  Then the exported file should contain only the filtered PO number rows


@SC-02 @SM-754
Scenario: Date filters narrow the Purchasing Tracker table and exported file reflects only the filtered date range
  Given I am logged in and on the dashboard
  When I navigate to the Purchasing Tracker
  And I apply the "Request Date" filter with a known date range
  Then the table should show only rows with Request Dates within that range
  When I click the "Export" button
  Then the exported file should contain only rows within the filtered Request Date range
  When I clear the "Request Date" filter
  And I apply the "Request By Date" filter with a specific future date
  Then the table should show only rows with Request By Dates matching that filter
  When I click the "Export" button
  Then the exported file should contain only rows matching the filtered Request By Date
  When I clear the "Request By Date" filter
  Then the table should display the full record set


@SC-03 @SM-754
Scenario: Dropdown and selection filters narrow the purchasing tracker table and export correctly
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  Then the Division column should have no filter option
  When I apply the "Type" column filter with value "PO"
  Then the table should show only rows matching type "PO"
  When I click the "Export" button
  Then the exported file should contain only rows with type "PO"
  When I clear the "Type" column filter
  And I apply the "Status" column filter with a single status value
  Then the table should show only rows matching that status
  When I click the "Export" button
  Then the exported file should contain only rows matching that status
  When I clear the "Status" column filter
  And I apply the "Priority" column filter with value "High"
  Then the table should show only high priority rows
  When I clear the "Priority" column filter
  And I apply the "Dept" column filter with a known department
  Then the table should show only rows for that department
  And the Dept column header should show a filter active indicator
  When I clear the "Dept" column filter
  Then the Dept column header should show no filter active indicator
  When I apply the "Vendor" column filter with a known vendor
  Then the table should show only rows for that vendor
  When I click the "Export" button
  Then the exported file should contain only rows for that vendor
  When I clear the "Vendor" column filter
  And I apply the "Requested Total" column filter greater than a known value
  Then the table should show only rows exceeding that requested total
  When I click the "Export" button
  Then the exported file should contain only rows matching the requested total filter
  When I clear the "Requested Total" column filter
  And I apply the "Needs My Approval" column filter with value "Yes"
  Then the table should show only records requiring my approval
  When I click the "Export" button
  Then the exported file should complete successfully with only matching rows


@SC-04 @SM-754
Scenario: Approval and Approver(s) column filters include Blank option and export reflects blank-only rows
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  Then the Purchasing Tracker grid should be visible
  When I open the filter for the "Approval" column
  Then the filter dropdown should include the options "Approved", "Pending Approval", "Override", "Rejected", and "Blank"
  When I select "Blank" from the "Approval" column filter
  Then all visible rows should have an empty "Approval" value
  And rows with a non-empty "Approval" value should not be visible
  When I click the "Export" button
  Then the exported file should contain only rows with a blank "Approval" value
  When I clear the "Approval" column filter
  And I open the filter for the "Approver(s)" column
  And I select "Blank" from the "Approver(s)" column filter
  Then all visible rows should have an empty "Approver(s)" value
  And rows with a named approver should not be visible
  When I click the "Export" button
  Then the exported file should contain only rows with a blank "Approver(s)" value


@SC-05 @SM-754
Scenario: Clearing filters resets the Purchasing Tracker table state and removes column header filter indicators
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply the "Dept" column filter with a known department
  Then the table should show only rows for that department
  And the Dept column header should show a filter active indicator
  When I clear the "Dept" column filter
  Then the table should display the full record set
  And the Dept column header should show no filter active indicator
  When I apply the "Status" column filter with a single status value
  And I apply the "Priority" column filter with value "High"
  Then both the Status and Priority column headers should show filter active indicators
  When I clear the "Status" column filter
  Then the Status column header should show no filter active indicator
  And the Priority column header should still show a filter active indicator
  When I clear all active filters
  Then the table should display the full record set
  And no column header should show a filter active indicator


@EC-01 @SM-754
Scenario: Blank column filters show all templates across text and dropdown column types
  Given I am logged in and on the dashboard
  When I navigate to the Cascade Templates admin screen
  And I apply a blank filter to the template name column
  And I apply a blank filter to the status column
  Then I should see the template list with available templates


@EC-02 @SM-754
Scenario: Export completes without freezing when the Purchasing Tracker has a large filtered result set
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply a broad "Status" filter that returns a large number of rows
  And I click the "Export" button
  And I navigate to the export queue and refresh until the export is ready
  Then the export file should be available for download and contain data rows



  # --- SM-754 scenarios added 2026-04-22 ---

@SC-01 @SM-754
Scenario: Text and numeric ID filters narrow the Purchasing Tracker table and export
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply the "ID" column filter with a known numeric purchase order ID
  Then the Purchasing Tracker table shows only the matching row
  When I export the Purchasing Tracker results
  Then the downloaded file contains only rows matching the filtered ID
  When I clear the "ID" column filter and apply the "WO#" column filter with a known work order number
  Then the Purchasing Tracker table shows only purchase orders linked to that work order number
  When I export the Purchasing Tracker results
  Then the downloaded file contains only the filtered rows and the WO# column is populated
  When I clear the "WO#" column filter and apply the "Description" column filter with a partial keyword
  Then the Purchasing Tracker table shows only rows where the description contains that keyword
  When I export the Purchasing Tracker results
  Then the downloaded file row count matches the filtered table row count


@SC-02 @SM-754
Scenario: Date-based filters narrow the Purchasing Tracker table and exported file reflects only the filtered date range
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I open the filter for the "Request Date" column
  Then the date filter should not offer an "Equal to" operator
  When I apply the "Request Date" filter using a "greater than or equal to" operator with a known date
  Then the table should show only rows with Request Date on or after that date
  When I click the "Export" button
  Then the exported file should contain only rows within the filtered Request Date range
  When I clear the "Request Date" column filter
  And I apply the "Request By Date" filter with a specific date condition
  Then the table should show only rows with Request By Date matching that condition
  When I click the "Export" button
  Then the exported file should contain only rows matching the filtered Request By Date
  When I clear the "Request By Date" column filter
  Then the table should display the full record set


@SC-03 @SM-754
Scenario: Dropdown filters narrow the list by Status, Type, Priority, and Vendor
  Given I am logged in and on the dashboard
  When I click the "Work Orders" sidebar parent menu
  And I click the "WO Tracker" sidebar menu item
  And I select "Open" from the "Status" dropdown filter
  And I select "Service" from the "Type" dropdown filter
  And I select "High" from the "Priority" dropdown filter
  And I select "Acme Corp" from the "Vendor" dropdown filter
  Then the list should display only items matching all selected filters


@SC-04 @SM-754
Scenario: People and department filters restrict export output — Assigned To, Dept, and Approvers
  Given I am logged in and on the dashboard
  When I navigate to the timesheet admin screen
  And I apply the "Assigned To" people filter
  And I apply the "Department" filter
  And I apply the "Approvers" filter
  And I click the "Export" button
  And I view the exports and refresh until the file is ready
  And I download the exported file
  Then the exported file should contain only rows matching the selected people and department filters


@SC-05 @SM-754
Scenario: Approval column dropdown filter includes a blank option and filters correctly
  Given I am logged in and on the dashboard
  When I click the "Vendors" sidebar parent menu
  And I click the "Vendor Admin" sidebar menu item
  And I open the dropdown filter on the "Approval" column
  Then the filter dropdown should include a blank option
  When I select the blank option from the "Approval" column filter
  Then the grid should display only vendors with no approval status assigned


@SC-06 @SM-754
Scenario: Approver(s) column blank filter shows only rows with no approver assigned
  Given I am logged in and on the dashboard
  When I navigate to the purchasing tracker
  And I apply a blank filter to the "Approver(s)" column
  Then only rows with no approver assigned should be visible in the grid
  And rows that have an approver assigned should not be displayed


@SC-07 @SM-754
Scenario: Needs My Approval Yes and Blank filters and Requested Total numeric filter narrow the table and export correctly
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply the "Needs My Approval" column filter with value "Yes"
  Then the table should show only records requiring my approval
  When I click the "Export" button
  Then the exported file should complete successfully with only matching rows
  When I clear the "Needs My Approval" column filter
  And I select "Blank" from the "Needs My Approval" column filter
  Then the table should show only rows where Needs My Approval is blank
  When I clear the "Needs My Approval" column filter
  And I apply the "Requested Total" column filter greater than a known value
  Then the table should show only rows exceeding that requested total
  When I click the "Export" button
  Then the exported file should contain only rows matching the requested total filter


@EC-01 @SM-754
Scenario: Sidebar filter text persists after navigation and clears when emptied
  Given I am logged in and on the dashboard
  When I type "Admin" in the sidebar filter
  Then the sidebar should show only menu items matching "Admin"
  When I click the "Dashboard" sidebar menu item
  Then the sidebar filter should still contain "Admin"
  When I type "" in the sidebar filter
  Then the sidebar should show all menu items


@EC-02 @SM-754
Scenario: Export completes and contains data rows when result set is large
  Given I am logged in and on the dashboard
  When I click the "Work Order Tracker" sidebar parent menu
  And I click the "WO Tracker" sidebar menu item
  And I click the "Export" button
  And I wait for the export to be ready in the export queue
  And I download the exported file
  Then the exported file should contain more than one data row



  # --- SM-754 scenarios added 2026-04-26 ---

@SC-01 @SM-754
Scenario: Core text and numeric filters narrow the Purchasing Tracker table and exports reflect the filtered rows
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply the "ID" column filter with a known numeric purchase order ID
  Then the Purchasing Tracker table shows only the matching row
  When I click the "Export" button
  Then the downloaded file contains only rows matching the filtered ID
  When I clear the "ID" column filter and apply the "WO#" column filter with a known work order number
  Then the Purchasing Tracker table shows only purchase orders linked to that work order number
  When I click the "Export" button
  Then the downloaded file contains only the filtered rows and the "WO#" column is populated
  When I clear the "WO#" column filter and apply the "Description" column filter with a partial keyword
  Then the Purchasing Tracker table shows only rows where the description contains that keyword
  When I click the "Export" button
  Then the downloaded file row count matches the filtered table row count


@SC-02 @SM-754
Scenario: Date-based filters narrow the Purchasing Tracker table and the export reflects the filtered date range
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I open the date filter for the "Request Date" column
  Then the "Equal to" operator should not be available in the date filter options
  When I apply the "Request Date" column filter using a "greater than or equal to" condition with a known date
  Then the Purchasing Tracker table shows only rows with a Request Date on or after that date
  When I export the Purchasing Tracker results
  Then the downloaded file row count matches the filtered table row count
  When I clear the "Request Date" column filter and apply the "Request By Date" column filter with a date condition
  Then the Purchasing Tracker table shows only rows with a Request By Date matching that condition
  When I export the Purchasing Tracker results
  Then the downloaded file row count matches the filtered table row count


@SC-03 @SM-754
Scenario: Categorical and dropdown filters narrow the Purchasing Tracker table and export, and clearing Dept filter removes the column header indicator
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply the "Type" column filter with a single type value
  Then the table should show only rows matching that type
  When I click the "Export" button
  Then the exported file should contain only rows matching that type
  When I clear the "Type" column filter
  And I apply the "Status" column filter with a single status value
  Then the table should show only rows matching that status
  When I click the "Export" button
  Then the exported file should contain only rows matching that status
  When I clear the "Status" column filter
  And I apply the "Priority" column filter with a known priority value
  Then the table should show only rows matching that priority
  When I clear the "Priority" column filter
  And I apply the "Vendor" column filter with a partial vendor name
  Then the table should show only rows matching that vendor
  When I click the "Export" button
  Then the exported file should contain only rows matching that vendor
  When I clear the "Vendor" column filter
  And I apply the "Dept" column filter with a known department
  Then the table should show only rows for that department
  And the Dept column header should show a filter active indicator
  When I clear the "Dept" column filter
  Then the table should display the full record set
  And the Dept column header should show no filter active indicator
  When I apply the "Dept" column filter with a known department
  And I click the "Export" button
  Then the exported file should contain only rows for that department


@SC-04 @SM-754
Scenario: Approval column filter shows all dropdown options including blank and export reflects active filter
  Given I am logged in and on the dashboard
  When I navigate to the timesheet admin screen
  And I open the column filter for "Approval"
  Then the filter dropdown should include "Approved", "Pending", "Rejected", "Blacklisted", and a blank option
  When I select the blank option from the "Approval" column filter
  Then the grid should display only rows with no approval status set
  When I click the "Export" button
  And I view the exports and refresh until the file is ready
  And I download the exported file
  Then the exported file should contain only rows matching the active blank approval filter


@SC-05 @SM-754
Scenario: Filter Approver(s) column by specific name, by blank, and export results
  Given I am logged in and on the dashboard
  When I click the "Vendors" sidebar parent menu
  And I click the "Vendor Admin" sidebar menu item
  And I filter the "Approver(s)" column by a specific approver name
  Then only rows matching that approver name should be visible in the grid
  When I filter the "Approver(s)" column by blank
  Then only rows with no approver assigned should be visible in the grid
  When I click the "Export" button
  And I navigate to the exports queue and refresh until the file is ready
  Then the exported file should contain only the blank-approver rows


@EC-01 @SM-754
Scenario: Sidebar filter text persists after navigation and clears when emptied
  Given I am logged in and on the dashboard
  When I type "Admin" in the sidebar filter
  Then the sidebar should show only menu items matching "Admin"
  When I click the "Dashboard" sidebar menu item
  Then the sidebar filter should still contain "Admin"
  When I type "" in the sidebar filter
  Then the sidebar should show all menu items


@EC-02 @SM-754
Scenario: Needs My Approval Yes filter resolves and exports; No filter is a known server performance limitation
  Given I am logged in and on the dashboard
  When I click the "Purchasing" sidebar parent menu
  And I click the "Purchasing Tracker" sidebar menu item
  And I apply the "Needs My Approval" column filter with value "Yes"
  Then the table should show only records requiring my approval
  When I click the "Export" button
  Then the exported file should complete successfully with only matching rows
  When I clear the "Needs My Approval" column filter
  And I apply the "Needs My Approval" column filter with value "No"
  Then the Purchasing Tracker page should remain interactive without freezing


@EC-03 @SM-754
Scenario: Multi-value filter selects multiple items simultaneously
  Given I am logged in and on the dashboard
  When I navigate to the Vendor Admin screen
  And I open the filter for the "Status" column
  And I select the filter value "Approved"
  And I select the filter value "Pending"
  And I apply the column filter
  Then the grid should display rows matching "Approved"
  And the grid should display rows matching "Pending"
  And no rows with other status values should be visible

