Feature: SM-864 — Test Plan: SM-864 — Vendor Admin AG Grid with Filters and Sorting
  Jira: SM-864
  Generated by bite step 6 on 2026-04-15

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard


  @TC-01 @SM-864
  Scenario: Navigate to Vendor Admin grid via sidebar
    When I click the "Vendor Admin" sidebar menu item
    Then I should see the page title "Vendor Admin"

  @TC-02 @SM-864
  Scenario: TC-02 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-02_log.md)
    Given TODO


  @TC-03 @SM-864
  Scenario: TC-03 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-03_log.md)
    Given TODO


  @TC-04 @SM-864
  Scenario: TC-04 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-04_log.md)
    Given TODO


  @TC-05 @SM-864
  Scenario: TC-05 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-05_log.md)
    Given TODO


  @TC-06 @SM-864
  Scenario: Column filter defaults to Contains and filters grid by partial company name
    When I click the "Vendors" sidebar parent menu
    And I click the "Vendor Admin" sidebar menu item
    Then I should see the Vendor Admin AG Grid
    When I open the column filter on the "Company Name" column
    Then the filter panel should be visible
    And the default filter operator should be "Contains"
    When I type "tech" in the column filter text input
    And I click the "Apply" button in the filter panel
    Then the AG Grid should only show rows where "Company Name" contains "tech"

  @TC-07 @SM-864
  Scenario: TC-07 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-07_log.md)
    Given TODO


  @TC-08 @SM-864
  Scenario: Column filter on Status displays distinct values and filters grid when applied
    When I click the "Vendor Admin" sidebar parent menu
    And I click the "Vendor Admin" sidebar menu item
    Then I should see the page title "Vendor Admin"
    When I open the column filter on the "Status" column
    Then I should see the set filter list with distinct values
    And the set filter should contain the value "Active"
    When I uncheck all values in the set filter
    And I select only the value "Active" in the set filter
    And I click the "Apply" button
    Then the grid should display only rows with "Status" value "Active"

  @TC-09 @SM-864
  Scenario: TC-09 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-09_log.md)
    Given TODO


  @TC-10 @SM-864
  Scenario: TC-10 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-10_log.md)
    Given TODO


  @TC-11 @SM-864
  Scenario: TC-11 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-11_log.md)
    Given TODO


  @TC-12 @SM-864
  Scenario: TC-12 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-12_log.md)
    Given TODO


  @TC-13 @SM-864
  Scenario: TC-13 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-13_log.md)
    Given TODO


  @TC-14 @SM-864
  Scenario: TC-14 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-14_log.md)
    Given TODO


  @TC-15 @SM-864
  Scenario: TC-15 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-15_log.md)
    Given TODO


  @TC-16 @SM-864
  Scenario: TC-16 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/TC-16_log.md)
    Given TODO


  @EC-01 @SM-864
  Scenario: EC-01 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/EC-01_log.md)
    Given TODO


  @EC-02 @SM-864
  Scenario: EC-02 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/EC-02_log.md)
    Given TODO


  @EC-03 @SM-864
  Scenario: EC-03 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/EC-03_log.md)
    Given TODO


  @EC-04 @SM-864
  Scenario: EC-04 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/EC-04_log.md)
    Given TODO


  @EC-05 @SM-864
  Scenario: EC-05 — TODO (generation failed, check /Users/kim/projects/github.com/fulcrum/powerslice/ps-site-slicer/bite/logs/SM-864/6_gherkin_scratch/EC-05_log.md)
    Given TODO


  @EC-06 @SM-864
  Scenario: Set filter select all and deselect all toggles grid rows
    When I click the "Vendor Admin" sidebar menu item
    Then I should see the page title "Vendor Admin"
    When I open the "Status" column filter
    And I deselect all values in the set filter
    And I click the "Apply" button
    Then the grid should display zero rows
    When I open the "Status" column filter
    And I select all values in the set filter
    And I click the "Apply" button
    Then the grid should display all rows

  @EC-07 @SM-864
  Scenario: Floating filter row has no CSS overlap with header or data rows
    When I click the "Vendor Admin" sidebar menu item
    Then I should see the page title "Vendor Admin"
    And the floating filter row should be visible below the column headers
    And the floating filter row should not overlap the header row
    And the floating filter row should not overlap the data rows
    When I scroll the grid vertically
    Then the floating filter row should remain properly aligned

  @EC-08 @SM-864
  Scenario: Vendor Admin AG Grid filter, sort, and column menu behavior is consistent with Project Tracker
    When I click the "Project Tracker" sidebar parent menu
    And I click the "Project Tracker" sidebar menu item
    Then I should see the AG Grid root element on the page
    When I open the column menu on a sortable column
    Then I should see the filter tab, general tab, and columns tab in the column menu
    When I close the column menu
    And I click the "Admin" sidebar parent menu
    And I click the "Vendor Admin" sidebar menu item
    Then I should see the AG Grid root element on the page
    When I open the column menu on a sortable column
    Then I should see the filter tab, general tab, and columns tab in the column menu
    And the Apply and Reset buttons should be visible in the filter panel
    And the Clear All Filters button should be visible in the grid toolbar

