Feature: SM-803 — Test Plan: SM-803 — Import Costs: Prevent Multiple Submissions
  Jira: SM-803
  Generated by TestGenerator step 6 on 2026-04-22

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-803
Scenario: Submit button disables on first click and processes once
  Given I am logged in and on the dashboard
  When I click the "Submit" button
  Then the "Submit" button should be disabled
  And the form should be submitted exactly once


@SC-02 @SM-803
Scenario: Rapid repeated clicks result in exactly one submission
  Given I am logged in and on the dashboard
  When I click the "Submit" button multiple times in rapid succession
  Then exactly one submission should be recorded


@SC-03 @SM-803
Scenario: Validation error keeps button functional for retry
  Given I am logged in and on the dashboard
  When I submit the form with missing required fields
  Then I should see a validation error message
  And I should see the "Save" button
  When I correct the required fields and click the "Save" button
  Then the form should be submitted successfully


@SC-04 @SM-803
Scenario: Submission failure allows user to retry
  Given I am logged in and on the dashboard
  When I click the "Submit" button
  Then I should see the "Submit" button


  @EC-01 @SM-803
  Scenario: EC-01 — TODO (generation failed)
    Given TODO


  @EC-02 @SM-803
  Scenario: EC-02 — TODO (generation failed)
    Given TODO

