Feature: SM-825 — Test Plan — SM-825: Vendor Mismatch on Case Sensitivity
  Jira: SM-825
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-825
Scenario: Vendor rename propagates to Quote Detail labor drivers
  Given I navigate to the Vendor Admin module
  And a vendor exists with a known name linked to a quote labor driver
  When I rename the vendor to a new name in Vendor Admin
  And I navigate to the Quote Detail for a quote that references that vendor
  Then the labor driver should display the updated vendor name
  And the old vendor name should not appear in the labor drivers list

@SC-02 @SM-825
Scenario: POR detail Required Vendors field matches PO Review Summary vendor name after vendor rename
  Given I am on the dashboard
  When I navigate to the Purchasing Tracker and open a purchase order detail for a vendor that has been renamed
  And I note the vendor name shown in the Required Vendors field
  And I navigate to the PO Review Summary for that purchase order
  Then the vendor name in the PO Review Summary should exactly match the Required Vendors field value

@SC-03 @SM-825
Scenario: Quote PO Console groups by updated vendor name and PO List column is current
  Given the vendor name has been updated in Vendor Admin
  When I navigate to the Quote PO Console
  Then the PO console should group purchase orders by the updated vendor name
  And the PO List column should display the current vendor name for all associated purchase orders

@SC-04 @SM-825
Scenario: Saving a quote re-injects vendor FK so a subsequent vendor rename propagates to the quote
  Given a quote exists that references a vendor by name
  When I open the quote and save it without changes
  And I rename the vendor in Vendor Admin to a new name
  And I reopen the same quote
  Then the quote displays the updated vendor name
  And the quote does not display the original vendor name

@SC-05 @SM-825
Scenario: Vendor PO widget on a work order displays the correct vendor name regardless of case
  Given I am logged in and on the dashboard
  When I open a work order that has a vendor assigned
  And I view the Vendor PO widget on the work order
  Then the vendor name displayed in the widget matches the assigned vendor exactly

@EC-01 @SM-825
Scenario: POs without FK still display vendor name via legacy fallback
  Given I am on the Purchasing Tracker page
  When I locate a purchase order that has no vendor foreign key association
  Then the Vendor Name column should still display the vendor name from the legacy text field

@EC-02 @SM-825
Scenario: Adding a vendor with a name that differs only by case is blocked
  Given I navigate to the Vendor Admin module
  And a vendor named "Acme Construction" already exists in Vendor Admin
  When I add a new vendor with the name "acme construction"
  Then I should see a duplicate name validation error
  And no new record should be created in the system
