Feature: SM-950 — Test Plan — SM-950: PWA Clock Simple Module
  Jira: SM-950
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-02 @SM-950
Scenario: Overlapping time period is rejected on submission
  Given I am logged in and on the dashboard
  And an existing time entry covers the current day
  When I submit a new time entry with a time period overlapping the existing entry
  Then I should see a validation message preventing the save

@SC-03 @SM-950
Scenario: Lunch validation error clears after a lunch option is selected
  Given I am logged in and on the dashboard
  When I navigate to the timesheet entry screen in the PWA
  And I attempt to submit a time entry without selecting a lunch option
  Then I should see a validation error message
  When I select a lunch option from the dropdown
  Then the lunch validation error should no longer be displayed

@SC-01 @SM-950
Scenario: Field technician successfully submits a Clock Simple entry from the PWA
  Given I navigate to the Clock Simple module in the PWA
  When I complete the clock entry form with a valid work order and submit
  Then exactly one submission should be recorded

@EC-01 @SM-950
Scenario: Work order search returns no results for an unrecognised search term
  Given I am logged in and on the dashboard
  When I navigate to the Work Orders module and search for "ZZZNOMATCH99999"
  Then I should see an empty results message

@SC-04 @SM-950
Scenario: New Period(s) section clears after a successful save
  Given I am logged in and on the dashboard
  When I navigate to the Timesheet module in the PWA
  And I fill in the New Period fields with a valid date and hours
  And I save the new timesheet period successfully
  Then the New Period input fields should be cleared and empty

@SC-05 @SM-950
Scenario: Side menu logout ends session and blocks re-access to dashboard
  Given I am logged in and on the dashboard
  When I click the logout option in the side menu
  Then I should see the username input field
  When I navigate directly to the dashboard
  Then I should see the username input field

@EC-02 @SM-950
Scenario: Date picker restricts selection to the current week only
  Given I am logged in and on the dashboard
  When I open the clock entry date picker in the PWA
  And I attempt to select a date outside the current week
  Then I should see a validation error message
