Feature: SM-905 — Test Plan: SM-905 — Department Mismatch Between User Admin and User Profile
  Jira: SM-905
  Generated by TestGenerator step 6 on 2026-05-06

  Background:
    Given I am on the login page
    When I enter my username
    And I click the next button
    And I enter my password
    And I click the "Let's go" button
    Then I should see the Safe Day's Alert modal
    When I dismiss the Safe Day's Alert
    Then I should be on the dashboard

@SC-01 @SM-905
Scenario: User Profile and User Admin display identical department name
  Given I am logged in and on the dashboard
  When I navigate to my User Profile and note the displayed department name
  And I navigate to User Admin and locate the same user record
  Then the department name in User Admin should match the department name from User Profile

@SC-02 @SM-905
Scenario: Admin updates a user's department and User Profile reflects it immediately
  Given I am logged in and on the dashboard
  When I navigate to the User Admin module
  And I open a user record for editing
  And I change the user's department to a different department
  And I save the user record
  Then the user's profile displays the updated department

@SC-03 @SM-905
Scenario: Company Directory list view shows department names not raw IDs
  Given I navigate to the Company Directory module
  When I view the employee list
  Then each employee record should display a department name not a numeric ID

@SC-04 @SM-905
Scenario: Company Directory user detail popup shows resolved department name
  Given I navigate to the Company Directory
  When I open the detail popup for a user who belongs to a department
  Then the popup should display the resolved department name rather than an ID

@SC-05 @SM-905
Scenario: Company Directory CSV export contains resolved department names
  Given I navigate to the Company Directory module
  When I export the Company Directory to CSV
  Then the downloaded file contains only the filtered rows and the "Department" column is populated

@EC-01 @SM-905
Scenario: User with no assigned department shows empty department field with no errors
  Given I am on the dashboard
  When I open the profile of a user who has no department assigned
  Then the department field should be empty
  And no error message should be displayed

@EC-02 @SM-905
Scenario: Saving User Profile does not overwrite the department assignment
  Given a user account has a department assigned in User Admin
  When I open that user profile and save it without changing the department field
  Then the department assignment should still be present and unchanged after saving
